.github/workflows/validate-test-coverage.yaml
Update and rename `test.yaml` to `validate-test-coverage.yaml`
N/A
---
=> Update and rename test.yaml to validate-test-coverage.yaml

.flake8, QUALITY.md, generator/scripts/add-imports.py, openworld/sdk/core/client/api.py, openworld/sdk/core/client/auth_client.py, openworld/sdk/core/configuration/auth_config.py, openworld/sdk/core/configuration/client_config.py, openworld/sdk/core/constant/body.py, openworld/sdk/core/model/authentication.py, openworld/sdk/core/model/error.py, pyproject.toml, requirements.txt
Add Quality Tools: `iSort`
Automatic import ordering.
---
=> feat(Quality): Add Quality Tools: iSort

.flake8, QUALITY.md, generator/scripts/add-imports.py, openworld/sdk/core/__init__.py, openworld/sdk/core/client/api.py, openworld/sdk/core/client/auth_client.py, openworld/sdk/core/configuration/auth_config.py, openworld/sdk/core/configuration/client_config.py, openworld/sdk/core/constant/constant.py, openworld/sdk/core/constant/header.py, openworld/sdk/core/constant/log.py, openworld/sdk/core/constant/message.py, openworld/sdk/core/constant/url.py, openworld/sdk/core/model/exception/service.py, openworld/sdk/core/setup.py, openworld/sdk/core/util/log.py, pyproject.toml, requirements.txt, validate_test_coverage.py
Add Quality Tools: `Black` - Reformat code style.
---
=> feat(Quality): Add Quality Tools: `Black`

.flake8, openworld/sdk/core/client/api.py, openworld/sdk/core/constant/body.py, openworld/sdk/core/constant/header.py, openworld/sdk/core/model/authentication.py, requirements.txt
Add Quality Tools: flake8-pep585 - Use the new types.
---
=> feat(Quality): Add Quality Tools: flake8-pep585

.github/dependabot.yml
=> chore(build): Setup Dependabot

openworld/sdk/core/core.config, openworld/sdk/core/setup.py
Support Dynamic Versioning: Add support for dynamic versioning parsed from a config file.
---
=> feat(build): Support Dynamic Versioning

.github/workflows/build-and-publish-core.yaml
=> build: update PyPi token

.github/workflows/build-and-publish-core.yaml
=> build: use PyPi prod URL

.github/workflows/generate-and-publish-sdk.yaml, .github/workflows/generate-sdk.yaml, .github/workflows/publish-sdk.yaml, generator/openapi/src/main/resources/templates/openworld-sdk/setup.handlebars, generator/scripts/generate.sh
=> build: add actions to generate and publish SDKs

openworld/sdk/core/requirements.txt, requirements.txt
- Add version of dependencies to requirements file.
-
=> chore(deps): Add version of dependencies to requirements file.

openworld/sdk/core/core.config
=> build: update core version

openworld/sdk/generator/client/templates/client.jinja2
- Fix User-Agent invalid parse which happens due to fetching data from a list into variables, in. which the list have more elements than the number of variables.
-
=> fix(generator): User-Agent invalid parse.

openworld/sdk/core/client/api.py, openworld/sdk/core/requirements.txt, openworld/sdk/core/setup.py, requirements.txt, test/core/constant/api.py, test/core/constant/authentication.py
- Replace `orjson` rust-based library with python's built-in native `json` library to ensure compatibility with different architectures and environments.
-
=> chore(core): Replace `orjson` rust-based with native `json`.

.github/workflows/generate-and-publish-sdk-experimental.yaml, .github/workflows/generate-sdk-experimental.yaml, openworld/sdk/generator/scripts/build-package.sh, openworld/sdk/generator/scripts/generate-client.sh, openworld/sdk/generator/scripts/generate-models.sh, openworld/sdk/generator/scripts/generate-sdk.sh
- Add git workflows to generate and publish SDKs using the new experimental generator.
-
=> build(git): Add git workflows to use new generator.

openworld/sdk/generator/client/templates/client.jinja2, openworld/sdk/generator/client/templates/setup.jinja2, openworld/sdk/generator/scripts/generate-models.sh
- Refactor `models` to `model` in generated code.
- Add `pydantic[email]` to setup.py
-
=> chore(generator): Update generator to generate code with the same experience as previous generator.

.github/workflows/generate-and-publish-sdk.yaml, .github/workflows/publish-sdk.yaml
=> chore: update release action to allow publishing to PyPi Test

openworld/sdk/generator/client/templates/client.jinja2
- Adds docstrings to generated clients.
-
=> chore(generator): Adds docstrings to generated clients.

openworld/sdk/generator/models/templates/Enum.jinja2
- Add docstrings to generated enum models.
-
=> chore(generator): Add docstrings to generated enum models.

openworld/sdk/generator/client/templates/client.jinja2
- chore(generator): Add transactionId to request headers.
=> chore(generator): Add transactionId to request headers.

openworld/sdk/generator/client/templates/__model__.jinja2, openworld/sdk/generator/client/visitors/models.py
- Adds Support for Multi-Level Inheritance.
- Moves not-needed and non-simple logic from templates to visitor, and simplifies the approach used to do type-aliasing.
- Replace python-native docstrings style with Google style.
=> feat(generator): Add Support for Multi-Level Inheritance.

openworld/sdk/core/requirements.txt, openworld/sdk/generator/resources/requirements.txt, requirements.txt
- Bump Up Pydantic Version.
- #116
=> chore(core, generator): Bump Up Pydantic Version.

openworld/sdk/core/core.config, openworld/sdk/generator/resources/requirements.txt
=> (chore) Update core version to 0.8.0

openworld/sdk/generator/client/visitors/sdk_info.py, openworld/sdk/generator/scripts/build-package.sh
generate sdk workflow, allow versions in namespace input
- 
-
=> fix: generate sdk workflow, allow versions in namespace input

openworld/sdk/generator/client/visitors/sdk_info.py
=> fix(git): Fix namespace and api name building.

openworld/sdk/generator/client/visitors/sdk_info.py
=> fix(generator): Spaces in API name.

.flake8, openworld/sdk/generator/client/parser.py, openworld/sdk/generator/client/templates/__model__.jinja2, openworld/sdk/generator/client/templates/client.jinja2, openworld/sdk/generator/scripts/generate-client.sh
- Fix lint issues in generated SDKs.
| Rule Violation | Example/Description                                                             | Fix                      |
|----------------|---------------------------------------------------------------------------------|--------------------------|
| F722           | syntax error in forward annotation `'^[A-Z]{3}$'`                               | IGNORE                   |
| W505           | doc line too long (189 > 160 characters)                                        | IGNORE                   |
| PEA001         | typing.List is deprecated, use list instead. See PEP 585 for details            | Fixed in Generator       |
=> chore(quality): Fix lint issues in generated SDKs

.flake8, openworld/sdk/generator/scripts/generate-client.sh
=> Omar al jarrah/update release dir lint rules

.github/workflows/generate-and-publish-sdk.yaml
- Skip publishing sources on test release.
-
=> chore(git): Skip publishing sources on test release.

.github/workflows/generate-and-publish-sdk.yaml
- Add spec endpoint to executor
N/A
=> chore(github): Add Spec Endpoint to Executor

openworld/sdk/core/requirements.txt, requirements.txt
- Bump up `pydantic` version to `1.10.12`
- Please do not approve any changes to the `pydantic` version.
-
=> chore(deps): Bump up `pydantic` version to `1.10.12`

README.md
=> chore(generator): Update README.md

expediagroup/sdk/core/setup.py
=> chore(deps): Set `pydantic` version in core's `setup.py`.

expediagroup/sdk/core/core.config, expediagroup/sdk/generator/resources/requirements.txt
=> chore(deps): Bump up core version.

expediagroup/sdk/core/client/api.py
=> chore(core): Include unset variables in requests.

.github/workflows/build-and-publish-core.yaml, .github/workflows/generate-sdk.yaml, .github/workflows/generator-main.yaml, .github/workflows/quality.yaml, .github/workflows/validate-test-coverage.yaml, expediagroup/sdk/core/core.config, expediagroup/sdk/generator/client/requirements.txt, expediagroup/sdk/generator/scripts/build-package.sh, expediagroup/sdk/generator/scripts/generate-sdk.sh, expediagroup/sdk/generator/scripts/generator-main.sh, requirements-core.txt, requirements-dev.txt, requirements-sdk.txt, requirements.txt
- Improve dependency management by improving the organization of dependency files.
- Add version parameter to core releasing workflow.
- Improves scripts and workflow naming.
-
=> chore(deps): Improve dependency management.

.github/workflows/generator-main.yaml, .github/workflows/publish-sdk.yaml
- Change workflow inputs to boolean
N/A
=> chore(workflows): Change Workflow Inputs to Boolean

.github/workflows/build-and-publish-core.yaml
=> chore(git): Update version input description in core releasing workflow.

requirements-sdk.txt
=> chore(git): Bump up core version.

requirements-dev.txt
=> chore(deps-dev): Add `autoflake-2.2.1` to `requirements-dev.txt` dependency file.

.github/workflows/generator-publish-sources.yaml
=> fix(git): Update `publish-sources` to meet new dependency management.

release/fraudPreventionV2/client.py, release/fraudPreventionV2/model.py, release/fraudPreventionV2/setup.py, release/fraudPreventionV2/specs.yaml
=> chore(releases): Update code and specs.

expediagroup/sdk/docsgen/__main__.py
=> fix(docs-generator): Optional templates path parameter issue.

expediagroup/sdk/generator/client/templates/setup.jinja2
- Fix repository url in setup.jinja2
N/A
=> fix(generation): Fix Repository URL in setup.jinja2

expediagroup/sdk/generator/client/templates/__model__.jinja2, expediagroup/sdk/generator/client/visitors/logs_config.py
=> chore(generator): Omit critical fields from logs.

requirements-docs.txt
Dut to conflict of dependencies with `mdformat-gfm`, this dependency is temporarily removed.
- 
-
=> fix(deps-dev): Remove `mdformat-frontmatter` dependency.

requirements-sdk.txt
=> chore(deps): Bump up SDK core version to `3.1.0`.

expediagroup/sdk/generator/client/templates/__model__.jinja2, release/fraudPreventionV2/src/model.py
=> chore(generator): Fix lint issues in generated SDKs.

release/fraudPreventionV2/src/client.py, release/fraudPreventionV2/src/model.py
=> refactor(releases): Run linters on release dir.

scripts/lint.sh
=> chore(quality): Add lint run script.

.github/workflows/contribution-lint.yaml, commitlint.config.js
=> feat(github): fix not latest commit only validated

.github/workflows/generator-draft-release.yaml
=> chore: fix draft releases action

requirements-dev.txt
=> chore(deps): set black major version to 23

expediagroup/sdk/core/setup.py, requirements-sdk.txt
=> chore(deps): replace pydantic v1 with v2 in setup file

expediagroup/sdk/core/constant/header.py, expediagroup/sdk/generator/client/templates/client.jinja2, requirements-dev.txt
- Downgrade Black dependency (https://github.com/koxudaxi/datamodel-code-generator/issues/1821)
- Update "user-agent" header value to match other SDK languages
- Add "x-sdk-title" to request headers
=> feat: update request headers

expediagroup/sdk/generator/client/templates/client.jinja2
- Remove transaction-id from method signatures
- Fix typos
=> feat: remove transaction-id from method signatures

requirements-sdk.txt
=> feat: upgrade core dependency

.github/workflows/contribution-lint.yaml
=> chore: run contribution lint validation on pr only
